version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: banksampah-app
    restart: unless-stopped
    ports:
      - "8001:80"      # Web App Port
      - "8989:8080"    # Laravel Reverb WebSockets Port
    environment:
      - APP_NAME=EcoBank
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=https://ecobank.my.id
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - SESSION_DRIVER=database
      - CACHE_STORE=database
      - QUEUE_CONNECTION=database
      - REVERB_APP_ID=856535
      - REVERB_APP_KEY=a5d7e6wrtwismkjqn5gn
      - REVERB_APP_SECRET=rb97eg7uumei0zzwhrpi
      - REVERB_HOST=0.0.0.0
      - REVERB_PORT=8080
      - REVERB_SCHEME=http
    volumes:
      - ./database:/var/www/html/database
      - app-storage:/var/www/html/storage/app

volumes:
  app-storage: